/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "rxfzwofrjcgfestqhxyi"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ4Znp3b2ZyamNnZmVzdHFoeHlpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzAyOTE5NjEsImV4cCI6MjA4NTg2Nzk2MX0.LhaGU-xhpfVOvMG7-urqI2eix2NL2qb6ST80uaCLkh0"